version: '3.8'
services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./:/app
    working_dir: '/app'
    networks:
      - fp

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_DATABASE: 'fpdb-test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'fp-mysql:/var/lib/mysql'
    networks:
      - fp

networks:
  fp:
    driver: bridge

volumes:
  fp-mysql:
    driver: local